fs: exfat: Allow using iversion.h on 4.14 kernel
We already have iversion.h now. Use it to fix compilation like following:

fs/exfat/inode.c:574:2: error: cannot increment value of type 'atomic64_t'
        inode_inc_iversion(inode);
        ^~~~~~~~~~~~~~~~~~~~~~~~~
fs/exfat/compat.h:24:52: note: expanded from macro 'inode_inc_iversion'

fs/exfat/inode.c:632:2: error: assigning to 'atomic64_t' from incompatible type 'int'
        inode_set_iversion(inode, 1);
        ^                         ~
fs/exfat/compat.h:28:58: note: expanded from macro 'inode_set_iversion'

2 errors generated.

Signed-off-by: atndko <z1281552865@gmail.com>
Signed-off-by: hachiman270 <hachiman270@gmail.com>
(cherry picked from commit 197c3e01b948203629987d12c4b6fd1bd8ac7d23)